### ISSUE TITLE
Need help about LeverageProfileID

### ISSUE THREAD

**Issue by miaolz123** [FXCMAPI/FC-examples#2]
I want to get my FXCM account's leverage (such as `100:1` / `200:1`), but I can only get `LeverageProfileID` of my account.

What is the relationship between leverage (such as `100:1` / `200:1`) and `LeverageProfileID` ?

Thanks a lot~

**Comment by FXCMAPI** [comment]
Unfortunately, this option is not available from ForexConnect API.

You can check it manually with ForexConnect  O2GTradingSettingsProvider.getMargins() function,
for example if for EUR/USD the MMR=13, and compare it with Margin requirements table for 100:1 leverage:
https://docs.fxcorporate.com/MMR-100-ltd-en.pdf
https://www.fxcm.com/uk/forex/trading-details/

Regards,
Daniel Halpert

**Comment by miaolz123** [comment]
thanks again!
